config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :vans, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :van
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :vans
  has_many :bookings
  # has_many :vans, through: :bookings, as: :booked_vans

  # validates :first_name, presence: true
  # validates :last_name, presence: true
end

app/models/van.rb
class Van < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many_attached :photos

  include PgSearch::Model
  pg_search_scope :search_by_model_and_location,
                  against: %i[model location listing_title description],
                  associated_against: {
                    user: [ :first_name, :last_name ]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  validates :listing_title, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:new, :create]

  def index
    @user_bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.van = @van
    if @booking.save
      redirect_to bookings_path, notice: "You successfully booked the van"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_booking
    @van = Van.find(params[:van_id])
  end
  def booking_params
    params.require(:booking).permit(:starting_date, :end_date, :num_guests)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/vans_controller.rb
class VansController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:query].present?
      # sql_query = <<~SQL
      #   vans.listing_title @@ :query
      #   OR vans.location @@ :query
      #   OR vans.description @@ :query
      #   OR vans.model @@ :query
      #   OR users.first_name @@ :query
      #   OR users.last_name @@ :query
      # SQL
      # @vans = Van.joins(:users).where(sql_query, query: "%#{params[:query]}%")
      @vans = Van.search_by_model_and_location("#{params[:query]}")
    else
      @vans = Van.all
    end
    @markers = @vans.geocoded.map do |van|
      {
        lat: van.latitude,
        lng: van.longitude,
        info_window: render_to_string(partial: "info_window", locals: { van: van }),
        image_url: helpers.asset_url("vanish_logo.png")
      }
    end
  end

  def new
    @van = Van.new
  end

  def show
    @van = Van.find(params[:id])
  end

  def create
    @van = Van.new(van_params)
    @van.user = current_user
    #save photo
    if @van.save
      redirect_to van_path(@van), notice: "Van was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def van_params
    params.require(:van).permit(:listing_title, :description, :model, :year, :bathroom, :kitchen, :dimentions, :capacity, :cost, :photos)
    # params.require(:van).permit(%i[listing_title description location cost model year mileage dimentions capacity fuel_type bathroom kitchen])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="top-margin">
  <h1>Your booked vans</h1>
  <div class="container-center">
    <% @user_bookings.each do |booking| %>
      <div class="card-trip card-trip-booking card-booking">
        <% booking.van.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        <% end  %>
          <div class="card-trip-infos">
            <div>
                <h2> <%= booking.van.listing_title %> </h2>
                  <p><%= booking.van.description %></p>
                  <p><%= booking.starting_date %></p>
                  <p><%= booking.end_date %></p>
                <%#   <% booking.van.photos.each do |photo| %>
                  <%#  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
                <%#     <% end %>
            </div>
                <h2 class="card-trip-pricing"><i class="fa-brands fa-bitcoin"></i> <%= booking.van.cost %>/night</h2>
              <%#   <img src="https://loremflickr.com/320/240/paris,girl/all" class="card-trip-user avatar-bordered" /> %>
              <%= cl_image_tag(booking.van.user.photo.key, :class => "card-trip-user avatar-bordered", crop: :thumb, gravity: :face) %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container-show">
  <div class="card" style="width: 50rem;">
    <%= cl_image_tag(@van.photos.first.key, class: "card-img-top") %>
    <!-- trying to use cl_tag to select first photo
    <img class="card-img-top" src="<% @van.photos.first %>" alt="photo of <% @van.listing_title %>">
    -->
    <div class="card-body">
      <!-- here we need to get information from the back end to populate our cards -->
      <h1 class="card-title"><%= @van.listing_title %></h1>
    </div>
    <div data-controller="total">
      <%= simple_form_for([@van, @booking]) do |f| %>
        <%# # <%= f.input :content %>
    

      <ul class="booking-list">
        <div>
        <%# # start date %>
        <%= f.input :starting_date, as: :date, html5: true, input_html: {data: {"total-target" => "start", action: "change->total#calculate"}} %>
    

        </div>
        <div>
        <%# # end date %>
        <%= f.input :end_date, as: :date, html5: true, input_html: {data: {"total-target" => "end", action: "change->total#calculate"}} %>
        </div>
        <%# # number of guest %>
      </ul>

    </ul>
      <ul class="booking-list">
        <div>
          <%= f.input :num_guests, input_html: {value: '1'}  %>
        </div>
        <div class="total-sum">
          <p class="total-text">Total:</p>
          <p><i class="fa-brands fa-bitcoin"></i></p>
          <p data-total-target="final">
            <%# <% (@booking.end_date - @booking.starting_date).to_i * @van.cost %>
            <%# <%= :end_date - :starting_date * :cost  %>
          </p>
        </div>

        
      </ul>



      <div class="center">
        <%= f.submit "Submit booking", class: "btn-checkout_book" %>
        <p class="cost" data-total-target="cost"> <%= @van.cost %> </p>
      </div>
      <% end %>
    </div>
      <!-- add font-awesome icon before each value (for bath/kitchen add line-through if false) -->

    <div class="card-body card-body-bottom">

    <%# <p class="card-link">Total:<i class="fa-brands fa-bitcoin"></i><%= @van.cost </p> %>
      <%# <a href="#" class="card-link btn-rent">Book</a> %>
    </div>
  </div>
</div>

app/views/layouts/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1597151116153-d2e8cb44fe41?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1032&q=80);">
  <div class="container">
    <%# <h1>The <strong>easisest way</strong> to rent your<strong> dream van</strong>!</h1> %>
    <h1>The easisest way to rent your dream van!</h1>
    <p>Destination: wherever you want to be.</p>
    <a class="btn-banner" href="/vans">Rent a van now!</a>
  </div>
</div>

app/views/layouts/_card.html.erb
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <!-- here we need to get information from the back end to populate our cards -->
    <h5 class="card-title">Name of Van</h5>
    <p class="card-text">Description from user about van.</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Kitchen</li>
    <li class="list-group-item">Bathroom</li>
    <li class="list-group-item">Stuff</li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link">Rent</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Marcus, Nicolas, Spencer, Preston <i class="fas fa-heart"></i> Le Wagoners
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag("vanish_logo.png", class:"vanish_logo_navbar") %>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Rent my Van", new_van_path, class: "btn-new" %>
          </li>
          <li class="nav-item dropdown">

          <% if user_signed_in? && !current_user.photo.key.nil? %>
            <div data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.photo.attached? ? cl_image_tag(current_user.photo.key, :class => "avatar dropdown-toggle", :id => "navbarDropdown", :width => 40, :height => 40, crop: :thumb, gravity: :face) : image_tag("vanish_logo.png", :class => "avatar dropdown-toggle", :id => "navbarDropdown", :width => 40, :height => 40) %>
            </div>
          <% else %>
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://res.cloudinary.com/itnb-sarl/image/upload/v1662027784/production/userlamda_w4ezrj.png" />
          <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <%= link_to "Rent my Van", new_van_path, class: "dropdown-item" %>
              <%= link_to "See my booking", bookings_path, class: "dropdown-item" %>
              <%= link_to "Edit my profile", edit_user_registration_path(@current_user), class: "dropdown-item" if user_signed_in? %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
              <%# <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a> %>
            <% end %>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vanish</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="wrapper">
      <div>
        <% unless current_page?(root_path) %>
        <%= render "layouts/navbar" %>
        <% end %>
        <%= yield %>
      </div>
      <div>
        <%= render "layouts/footer" %>
      </div>
    </div>

    <%= render "shared/flashes" %>
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<%# <%= render "layouts/navbar" %>
<%= render "layouts/banner" %>
<%# <%= render "layouts/footer" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/vans/_form.html.erb
<%= f.input :location,
  input_html: {data: {address_autocomplete_target: "location"}},
  wrapper_html: {data: {controller: "location-autocomplete", location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/vans/_info_window.html.erb
<h2><%= van.listing_title %></h2>
<p><%= van.location %></p>

app/views/vans/index.html.erb
<div class="container nb-search-bar">
  <%= form_with url: vans_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control nb-rounded-left",
      placeholder: "Find a van"
    %>
    <%= submit_tag "Search", class: "btn btn-primary nb-rounded-right" %>
  <% end %>
</div>
<div class="d-flex justify-content-between">
  <div class="container-vanshowpage " style="width:40vw;">
    <% @vans.each do |van| %>
    <a href= <%= "vans/#{van.id}" %> >
      <div class="card-trip col-4">
      <% van.photos.each do |photo| %>
        <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
      <% end  %>
        <div class="card-trip-infos">
          <div>
              <h2> <%= van.listing_title %> </h2>
                <p><%= van.description %></p>
              <%#   <% van.photos.each do |photo| %>
                <%#  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
              <%#     <% end %>
          </div>
              <h2 class="card-trip-pricing"><i class="fa-brands fa-bitcoin"></i> <%= van.cost %>/night</h2>
            <%#   <img src="https://loremflickr.com/320/240/paris,girl/all" class="card-trip-user avatar-bordered" /> %>
            <%= cl_image_tag(van.user.photo.key, :class => "card-trip-user avatar-bordered", crop: :thumb, gravity: :face) %>
        </div>
      </div>
      </a>
      <% end %>
    </div>
  <div style="width: 40vw; height: 100vh; position: sticky; top: 0;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/vans/new.html.erb
<div class="container-show">
  <div class="card" id="card-new-booking">
    <div class="card-body">
      <h1 class="card-title">Please, fill the form to rent your van</h1>
          <%= simple_form_for(@van) do |f| %>
            <%= f.input :listing_title, label: "Give a name to your van:", input_html: { class: 'nb-rounded' } %>
            <%= f.input :location, label: "Give the address where to pickup your van :", input_html: { class: 'nb-rounded' } %>
            <%= f.input :photos, as: :file, input_html: { class: 'nb-rounded' } %>
            <div class="nb-model">
              <div class="nb-space-right">
                <%= f.input :model, label: "Model of your van (Ford Transit, Volkswage California...)", input_html: { class: 'nb-rounded' } %>
              </div>
              <%= f.input :year, label: "Model Year", input_html: { class: 'nb-rounded' }  %>
            </div>
            <div class="nb-model">
              <div class="nb-space-right">
                <%= f.input :capacity, label: "How many people can sleep inside ?", input_html: { class: 'nb-rounded' } %>
              </div>
            <%= f.input :dimentions, label: "How big is your van ? (W x H)", input_html: { class: 'nb-rounded' } %>
            </div>
            <p class="nb-rounded">Select the equipments :</p>
            <div class="nb-model">
              <div class="nb-space-right">
                <%= f.input :bathroom, input_html: { class: 'nb-rounded' } %>
              </div>
            <%= f.input :kitchen, input_html: { class: 'nb-rounded' } %>
             </div>
            <div class="nb-cost">
              <%= f.input :cost, label: "Enter the price per night", input_html: { class: 'nb-rounded' } %>
              <i class="fa-brands fa-bitcoin"></i>
            </div>
            <%= f.input :description, input_html: { class: 'nb-rounded' } %>
            <!-- [...] -->
            <div class="center">
              <%= f.submit "Rent my van", class: "btn-checkout_book" %>
            </div>
          <% end %>
    </div>
  </div>
</div>

app/views/vans/show.html.erb
<div class="container-show">
  <div class="card" style="width: 42rem;">
    <%= cl_image_tag(@van.photos.first.key, class: "card-img-top") %>
    <!-- trying to use cl_tag to select first photo
    <img class="card-img-top" src="<% @van.photos.first %>" alt="photo of <% @van.listing_title %>">
    -->
    <div class="card-body">
      <!-- here we need to get information from the back end to populate our cards -->
      <h1 class="card-title"><%= @van.listing_title %></h1>
      <h4 class="card-text"><%= @van.description %></h4>
    </div>
    <ul class="list">
      <div>
        <li class="list-group-item"><i class="fa-solid fa-users"></i><%= @van.capacity %></li>
        <li class="list-group-item"><i class="fa-solid fa-arrows-left-right"></i><%= @van.dimentions %></li>
        <li class="list-group-item"><i class="fa-solid fa-bus-simple"></i><%= @van.model %></li>
        <li class="list-group-item"><i class="fa-solid fa-calendar"></i><%= @van.year %></li>
        <li class="list-group-item"><i class="fa-solid fa-gauge-high"></i><%= @van.mileage %></li>
      </div>
      <div>
        <li class="list-group-item"><i class="fa-solid fa-gas-pump"></i><%= @van.fuel_type %></li>
        <li class="list-group-item"><i class="fa-solid fa-location-dot"></i><%= @van.location %></li>
        <li class="list-group-item"><i class="fa-solid fa-toilet"></i>Bathroom</li>
        <li class="list-group-item"><i class="fa-solid fa-sink"></i></i>kitchen</li>
      </div>
      <!-- add font-awesome icon before each value (for bath/kitchen add line-through if false) -->
    </ul>
    <div class="card-body card-body-bottom">
    <p class="card-link">Total:<i class="fa-brands fa-bitcoin"></i><%= @van.cost %></p>

      <%= link_to "Rent", new_van_booking_path(@van), class: "card-link btn-rent" %>
    </div>
  </div>
</div>